import './globals.css'
import type { Metadata } from 'next'

{/** font */}
import {Sora} from '@next/font/google';

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500','600', '700', '800']
});

{/**component */}
import { Nav, Header, TopLeftImg} from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <div className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative h-full`}>
    <TopLeftImg/>
    <Nav/>
    <Header/>

    {children}
   </div>
  )
}
